# Generated by Django 3.0.3 on 2020-09-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='staff',
            new_name='student',
        ),
    ]
