# Generated by Django 3.0.3 on 2020-09-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockapp', '0002_auto_20200915_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='achievements',
            field=models.TextField(choices=[(1, 'proffessor'), (2, 'asst_professor')], max_length=200),
        ),
    ]
