# Generated by Django 3.0.3 on 2020-09-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockapp', '0003_auto_20200915_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='achievements',
            field=models.TextField(choices=[('abc', 'proffessor'), ('vgh', 'asst_professor')], max_length=200),
        ),
    ]
