# Generated by Django 3.0.3 on 2020-09-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockapp', '0004_auto_20200915_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='achievements',
            field=models.TextField(choices=[('professor', 'proffessor'), ('assistant_professor', 'asst_professor')], max_length=200),
        ),
    ]
