# Generated by Django 3.0.3 on 2020-09-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockapp', '0005_auto_20200915_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='activation_key',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='staff',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='privkey',
            field=models.CharField(default=0, max_length=5000, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='pubkey',
            field=models.CharField(default=0, max_length=5000, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='activation_key',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='privkey',
            field=models.CharField(default=0, max_length=5000, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pubkey',
            field=models.CharField(default=0, max_length=5000, unique=True),
        ),
    ]
