# Generated by Django 3.0.3 on 2020-09-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockapp', '0006_auto_20200915_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='achievements',
            new_name='achievement',
        ),
    ]
