# Generated by Django 3.0.3 on 2020-09-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockapp', '0008_auto_20200917_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('inhash', models.CharField(max_length=40)),
                ('prevhash', models.CharField(max_length=40)),
                ('transaction', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('proof', models.BooleanField(max_length=40)),
                ('noance', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
