# Generated by Django 3.0.3 on 2020-09-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockapp', '0009_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='next1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blockapp.Block'),
        ),
    ]
