# Generated by Django 3.0.3 on 2020-09-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockapp', '0010_block_next1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='noance',
            new_name='nonce',
        ),
        migrations.AddField(
            model_name='block',
            name='blk_id',
            field=models.IntegerField(default=0),
        ),
    ]
