# Generated by Django 3.0.3 on 2020-09-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockapp', '0011_auto_20200921_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='next1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blockapp.block'),
        ),
    ]
