# Generated by Django 3.0.3 on 2020-10-01 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockapp', '0012_auto_20200921_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='next1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockapp.block'),
        ),
    ]
