# Generated by Django 3.0.3 on 2020-10-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockapp', '0013_auto_20201001_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='next1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockapp.block'),
        ),
        migrations.AlterField(
            model_name='block',
            name='nonce',
            field=models.IntegerField(null=True),
        ),
    ]
