# Generated by Django 3.0.3 on 2020-10-08 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockapp', '0016_auto_20201006_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='transactionid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='block',
            name='next1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockapp.block'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='proof',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='staff',
            field=models.CharField(default='abc', max_length=40),
        ),
    ]
