# Generated by Django 3.0.3 on 2020-08-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privkey',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='pubkey',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
