# Generated by Django 3.0.3 on 2020-08-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200827_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privkey',
            field=models.CharField(default='abc', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='pubkey',
            field=models.CharField(default='abc', max_length=500),
        ),
    ]
