# Generated by Django 3.0.3 on 2020-08-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200827_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privkey',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pubkey',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
    ]
