# Generated by Django 3.0.3 on 2020-08-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200827_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privkey',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pubkey',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
