# Generated by Django 3.0.3 on 2020-09-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200828_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privkey',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pubkey',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
