# Generated by Django 3.0.3 on 2020-09-15 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20200915_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_validated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='privkey',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pubkey',
        ),
    ]
