# Generated by Django 3.0.3 on 2020-09-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20200915_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='privkey',
            field=models.CharField(default=0, max_length=5000, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pubkey',
            field=models.CharField(default=0, max_length=5000, unique=True),
        ),
    ]
