# Generated by Django 3.0.3 on 2020-09-17 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockapp', '0008_auto_20200917_2003'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0022_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.IntegerField()),
                ('department', models.CharField(max_length=15)),
                ('achievement', models.TextField(choices=[('professor', 'proffessor'), ('assistant_professor', 'asst_professor')], max_length=200)),
                ('activation_key', models.CharField(default=1, max_length=255)),
                ('email_validated', models.BooleanField(default=False)),
                ('pubkey', models.CharField(default=0, max_length=5000, unique=True)),
                ('privkey', models.CharField(default=0, max_length=5000, unique=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('rollno', models.IntegerField()),
                ('achievements', models.TextField(max_length=200)),
                ('activation_key', models.CharField(default=1, max_length=255)),
                ('email_validated', models.BooleanField(default=False)),
                ('pubkey', models.CharField(default=0, max_length=5000, unique=True)),
                ('privkey', models.CharField(default=0, max_length=5000, unique=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.TextField(max_length=200)),
                ('is_voted', models.BooleanField(default=False)),
                ('votes', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Student')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
