# Generated by Django 3.0.3 on 2020-09-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20200917_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='privkey',
            field=models.CharField(default=0, max_length=5000),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pubkey',
            field=models.CharField(default=0, max_length=5000),
        ),
    ]
