# Generated by Django 3.0.3 on 2020-09-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20200918_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='achievement',
            new_name='category',
        ),
    ]
